# Generated by Django 5.0.6 on 2024-06-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='in_stock',
            field=models.IntegerField(default=0),
        ),
    ]
